# Generated by Django 4.1.6 on 2023-04-11 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipmentProductName', models.CharField(max_length=1000)),
                ('bindingsProductName', models.CharField(max_length=1000)),
                ('bootsProductName', models.CharField(max_length=1000)),
                ('skillLevel', models.CharField(choices=[('Beginner', 'BEGINNER'), ('Intermediate', 'INTERMEDIATE'), ('Advanced', 'ADVANCED'), ('Expert', 'EXPERT')], default='Beginner', max_length=25)),
                ('equipmentHeight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bootSize', models.DecimalField(decimal_places=1, max_digits=10)),
                ('wearStatus', models.CharField(choices=[('Factory-New', 'FACTORY-NEW'), ('Minimal-Wear', 'MINIMAL-WEAR'), ('Field-Tested', 'FIELD-TESTED'), ('Well-Worn', 'WELL-WORN'), ('Battle-Scarred', 'BATTLE-SCARRED')], default='Factory-New', max_length=25)),
                ('equipmentType', models.CharField(choices=[('Ski', 'SKI'), ('Snowboard', 'SNOWBOARD')], default='Ski', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(choices=[('Shadyside', 'SHADYSIDE'), ('Squirrel Hill North', 'SQUIRREL HILL NORTH'), ('Squirrel Hill South', 'SQUIRREL HILL SOUTH'), ('Oakland', 'OAKLAND'), ('East Libery', 'EAST LIBERTY'), ('Downtown', 'DOWNTOWN'), ('Southside', 'SOUTHSIDE')], default='Shadyside', max_length=25)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Unspecified', 'UNSPECIFIED')], default='Male', max_length=25)),
                ('bootSize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userType', models.CharField(choices=[('Ski', 'SKI'), ('Snowboard', 'SNOWBOARD')], default='Ski', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('equipmentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.equipment')),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('equipmentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.equipment')),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(max_length=50)),
                ('equipmentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='profileId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.profile'),
        ),
    ]
