# Generated by Django 4.1.6 on 2023-05-01 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment_product_name', models.CharField(max_length=1000)),
                ('bindings_product_name', models.CharField(max_length=1000)),
                ('boots_product_name', models.CharField(max_length=1000)),
                ('skill_level', models.CharField(choices=[('Beginner', 'BEGINNER'), ('Intermediate', 'INTERMEDIATE'), ('Advanced', 'ADVANCED'), ('Expert', 'EXPERT')], default='Beginner', max_length=25)),
                ('equipment_height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boot_size', models.DecimalField(decimal_places=1, max_digits=10)),
                ('wear_status', models.CharField(choices=[('Factory-New', 'FACTORY-NEW'), ('Minimal-Wear', 'MINIMAL-WEAR'), ('Field-Tested', 'FIELD-TESTED'), ('Well-Worn', 'WELL-WORN'), ('Battle-Scarred', 'BATTLE-SCARRED')], default='Factory-New', max_length=25)),
                ('equipment_type', models.CharField(choices=[('Ski', 'SKI'), ('Snowboard', 'SNOWBOARD')], default='Ski', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('neighborhood', models.CharField(choices=[('Shadyside', 'SHADYSIDE'), ('Squirrel Hill North', 'SQUIRREL HILL NORTH'), ('Squirrel Hill South', 'SQUIRREL HILL SOUTH'), ('Oakland', 'OAKLAND'), ('East Liberty', 'EAST LIBERTY'), ('Downtown', 'DOWNTOWN'), ('Southside', 'SOUTHSIDE')], default='Shadyside', max_length=25)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Unspecified', 'UNSPECIFIED')], default='Male', max_length=25)),
                ('boot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_type', models.CharField(choices=[('Ski', 'SKI'), ('Snowboard', 'SNOWBOARD')], default='Ski', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.equipment')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_listings', to='skieasy_app.equipment')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('content_type', models.CharField(max_length=50)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skieasy_app.profile'),
        ),
    ]
