# Generated by Django 4.1.6 on 2023-04-10 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(choices=[('Shadyside', 'SHADYSIDE'), ('Squirrel Hill North', 'SQUIRREL HILL NORTH'), ('Squirrel Hill South', 'SQUIRREL HILL SOUTH'), ('Oakland', 'OAKLAND'), ('East Libery', 'EAST LIBERTY'), ('Downtown', 'DOWNTOWN'), ('Southside', 'SOUTHSIDE')], default='Shadyside', max_length=25)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Unspecified', 'UNSPECIFIED')], default='Male', max_length=25)),
                ('bootSize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userType', models.CharField(choices=[('Ski', 'SKI'), ('Snowboard', 'SNOWBOARD')], default='Ski', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
