# Generated by Django 4.1.6 on 2023-05-02 02:00

from django.db import migrations, models
import skieasy_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('skieasy_app', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlisting',
            name='start_date',
            field=models.DateTimeField(validators=[skieasy_app.models.validate_start_date]),
        ),
        migrations.AlterField(
            model_name='equipmentreservation',
            name='start_date',
            field=models.DateTimeField(validators=[skieasy_app.models.validate_start_date]),
        ),
    ]
