# Generated by Django 4.1.6 on 2023-05-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skieasy_app', '0003_alter_equipmentlisting_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='content_type',
            field=models.CharField(default='jpg', max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='picture',
            field=models.FileField(default='default.png', upload_to=''),
        ),
    ]
